access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_SHARED_0}.${MONGODB_CLUSTER}.${MONGODB_HOST}:${MONGODB_PORT},${MONGODB_SHARED_1}.${MONGODB_CLUSTER}.${MONGODB_HOST}:${MONGODB_PORT},${MONGODB_SHARED_2}.${MONGODB_CLUSTER}.${MONGODB_HOST}:${MONGODB_PORT}/?${MONGODB_PROPERTIES}
      database: ${MONGODB_DB}
logging:
  level:
    org.springframework.security: DEBUG
