ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
MONGODB_USERNAME: "arojas"
MONGODB_PASSWORD: "giPC6lgTLwxeIits"
MONGODB_HOST: "mongodb.net"
MONGODB_PORT: "27017"
MONGODB_SHARED_0: "ac-hgetq2i-shard-00-00"
MONGODB_SHARED_1: "ac-hgetq2i-shard-00-01"
MONGODB_SHARED_2: "ac-hgetq2i-shard-00-02"
MONGODB_CLUSTER: "h5cxzg7"
MONGODB_DB: "doczy"

#MONGODB_RS: "rs1"
MONGODB_PROPERTIES: "ssl=true&replicaSet=atlas-nkjr32-shard-0&authSource=admin&retryWrites=true&w=majority"
